vo=gpu-next
hwdec=no
gpu-api=opengl
video-sync=display-resample
profile=high-quality
fs
#ytdl-format=bestvideo[vcodec][height<=1080]+bestaudio/best
ytdl-format=bestvideo[vcodec^=avc1][height<=1080]+bestaudio/best
