# MPV configuration file for Linux

vo=gpu-next

#vo=gpu

#hwdec=auto-copy

#hwdec=vaapi
hwdec=vaapi-copy

gpu-api=opengl

#video-sync=display-resample

#profile=high-quality
profile=fast

fs

audio-pitch-correction=no
no-border

#ytdl-format=bestvideo[vcodec][height<=1080]+bestaudio/best
#ytdl-format=bestvideo[height<=1080]+bestaudio/best

ytdl-format="bestvideo[height<=1080][vcodec^=avc1]+bestaudio/best